var num=10; 
var num1=20;
var calculadora = { 
    somar: num+num1, 
    dividir: num/num1,
    multiplicar: num*num1,
    subtrair: num-num1, 

}

console.log("O valor da some é: " + calculadora.somar); 
console.log("O valor da divisão é: " + calculadora.dividir); 
console.log("O valor da multiplicação é: " + calculadora.multiplicar); 
console.log("O valor da subtração é: " + calculadora.subtrair); 
